server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      open-in-view: true
  profiles:
    active: dev
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: default
graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /graphql
    cors-enabled: true
    tracing-enabled: true
    actuator-metrics: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
  extended-scalars: BigDecimal, Date
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: TK Book
        query: classpath:graphql/booktk.graphqls
        variables: classpath:graphql/booktk_variables.json
    enabled: true

#  annotations:
#    base-package: com.example.graphl.schema # required
#    always-prettify: true
#    true is the default value, no need to specify it
#    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
#    # specification and expectations of most clients, so use this option with caution
#    introspection-enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
